### ISSUE TITLE
Disabling 2FA

### ISSUE THREAD

**Issue by viktorix** [KTS915/Test-ClassicPress-Directory#13] opened 2022-07-25 14:58 UTC
I tried disabling 2FA by resetting the key. I can continue to do everything as if 2FA is still on, like submitting forms. Is this the intended result? I would assume 2FA is permanently required, so disabling it should cause enable previous restrictions. Or disable the option to disable 2FA.

**Comment by KTS915** [comment] 2022-07-25 15:04
No, that's not intended. I pushed some code last night that I thought prevented this. I will take another look. Thanks for pointing this out.

**Comment by viktorix** [comment] 2022-07-25 15:08
Let me know when you update it, I'll test it again.

**Comment by KTS915** [comment] 2022-07-25 15:19
Are you sure you actually managed to disable 2FA? When I try this, the profile says it has updated, but 2FA by Email is still set. (This is the recommended default since everyone can use it.) So you can still do what you would be able to do with 2FA on because it is.

**Comment by viktorix** [comment] 2022-07-25 15:21
It looks disabled. I've tested OTP code.
![image](https://user-images.githubusercontent.com/1692600/180815043-6eb97a85-2a3d-4e4a-9e7c-cc4298eb5ba2.png)

**Comment by KTS915** [comment] 2022-07-25 16:07
In that case, it _is_ disabled! Hmm, I'm not seeing this on my end. Will investigate further...

**Comment by KTS915** [comment] 2022-07-27 20:17
Addressed by commit to `mu-plugins -> `two-factor.php` (Not sure why comments on that commit haven't automatically led to the commit appearing here.)

**Comment by KTS915** [comment] 2022-07-27 20:18
@viktorix Feel free to test removal of 2FA now.

**Comment by viktorix** [comment] 2022-07-27 20:33
@KTS915 thanks. The email authentication option is enabled now and cannot be disabled. However, when I log out and try to log back in, there is no prompt for the email code. It lets me in without 2FA code. And since email authentication is always enabled, submission forms are also available as far as I can tell. Is that intended behavior?

![image](https://user-images.githubusercontent.com/1692600/181366573-727f27a7-7844-4ae7-8115-f741e869f9df.png)

**Comment by KTS915** [comment] 2022-07-27 21:05
This sounds like a bug with the Two Factor plugin, as the code I've used is just copied from their recommendation on their Github repo. I will investigate further.

**Comment by KTS915** [comment] 2022-07-27 21:33
I now think that this is not so much a bug in the plugin as an incomplete recommendation for what's required, as the code they recommend doesn't update the relevant field in the database. I've now added a line of code to do that, and it seems to work now. Please try it when you get the chance.

**Comment by viktorix** [comment] 2022-08-04 03:54
So right now, email 2FA is a forced option that cannot be disabled. If I switch to OTP option, it works. But if I try to disable OTP option, it reverts back to email 2FA enabled and set as primary. So it's not possible to have 2FA disabled. If that's how it should be, then it's all good.

**Comment by KTS915** [comment] 2022-08-04 16:16
Yes, this is as intended. The user can choose their preferred method of 2FA but, if they try to deactivate it altogether, the email method gets set for them regardless. (This method is the one chosen because it will work for everyone.)

**Closed as completed by KTS915** 2022-08-04 16:16 UTC
